version: '3'
services:
    greenshare:
        container_name: 'greenshare-server'
        image: 'raulplesa/greenshare-server:latest'
        depends_on:
            - 'mariadb'
        ports:
            - '80:13000'
            - '443:13443'
        restart: unless-stopped
        volumes:
            - './.env:/app/.env'
    mariadb:
        container_name: 'mariadb'
        image: 'mariadb:10'
        environment:
            - 'MARIADB_PASSWORD=p4ssw0rd'
            - 'MARIADB_USER=user'
            - 'MARIADB_DATABASE=greenshare'
            - 'MARIADB_RANDOM_ROOT_PASSWORD=yes'
        volumes:
            - './mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql'
            - './mariadb/dbdata:/var/lib/mysql'
